name: "Run Tests"
description: "Runs Anchor tests"
inputs:
  program:
    description: "Program to test"
    required: true
  solana_version:
    description: "Solana version used for cache"
    required: true
    default: ""
  anchor_version:
    description: "Anchor version used for cache"
    required: true
    default: ""
  features:
    description: "Features that will be passed into the test"
    required: false

runs:
  using: "composite"
  steps:
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ./node_modules/
        key: node-modules-${{ runner.os }}-build-v0.1

    - name: Install Node.js dependencies
      shell: bash
      run: yarn install

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-directories: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          test-ledger/
        shared-key: "anchor-test-${{ inputs.anchor_version }}-${{ inputs.solana_version }}"

    - name: Run Anchor Tests
      shell: bash
      env:
        CARGO_INCREMENTAL: 1
        CARGO_NET_RETRY: 10
        RUST_BACKTRACE: 1
      run: |
        echo "Running tests for program: ${{ inputs.program }}"
                FEATURES="${{ inputs.features }}"
        if [ ! -z "$FEATURES" ]; then
          FEATURES="--features $FEATURES"
        fi

        anchor test -- $FEATURES

    - name: Check Test Results
      if: ${{ failure() }}
      shell: bash
      run: |
        echo "Tests failed! Check the logs above for details."
        exit 1
